### ISSUE TITLE
@anirudha, do you have examples of the Gantt charts this plugin is going to render?

### ISSUE THREAD

**Issue by jcgraybill** [opendistro-for-elasticsearch/kibana-visualizations#10]
@anirudha, do you have examples of the Gantt charts this plugin is going to render?

I am working on a timeline chart at work using [Vega](https://vega.github.io/vega) and I'm planning to make a Kibana plugin out for it, but I would prefer using this Gantt chart instead if it meets my requirements.

_Originally posted by @cascandaliato in https://github.com/opendistro-for-elasticsearch/community/issues/210#issuecomment-728120799_

**Comment by anirudha** [comment]
the Gantt chart usage is documented here with an example
https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/gantt/
